export type Role =
    | 'Super Admin'
    | 'HR Manager'
    | 'Payroll Officer'
    | 'Branch Manager'
    | 'Device Admin'
    | 'Employee';

export type Permission =
    | 'organisation.manage'
    | 'settings.manage'
    | 'users.manage'
    | 'employees.view'
    | 'employees.create'
    | 'employees.update'
    | 'employees.delete'
    | 'salaries.view'
    | 'salaries.manage'
    | 'shifts.view'
    | 'shifts.manage'
    | 'holidays.manage'
    | 'attendance.view'
    | 'attendance.manage'
    | 'overtime.approve'
    | 'leaves.view'
    | 'leaves.manage'
    | 'leaves.approve'
    | 'adjustments.view'
    | 'adjustments.manage'
    | 'payroll.view'
    | 'payroll.run'
    | 'payroll.approve'
    | 'payroll.pay'
    | 'devices.view'
    | 'devices.manage'
    | 'biometrics.manage'
    | 'backups.manage'
    | 'reports.view'
    | 'self-service.access';
